spring:
  application:
    name: virtual-card-service
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

# Server port
server:
  port: ${SERVER_PORT:8080}
#  servlet:
#    context-path: /api/virtual-card

# Default logging
logging:
  level:
    root: INFO
